name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Install Nix
        uses: cachix/install-nix-action@b97f05dcb019ddea06450a50ef6203d2fdc19fee # v31
      - name: Set up Cachix
        uses: cachix/cachix-action@97e5ff84d02b3b4f9936339f767e17f03c9252ed # v16
        with:
          name: fleet-nixos
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run root flake checks and builds
        run: nix flake check # Note, check includes build of orbit.
      - name: Run development flake checks
        run: nix flake check ./dev
